# Generated by Django 3.1.3 on 2021-02-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecipeName', models.CharField(max_length=155, null=True)),
                ('TranslatedRecipeName', models.CharField(max_length=155, null=True)),
                ('Ingredients', models.CharField(max_length=155, null=True)),
                ('TranslatedIngredients', models.CharField(max_length=155, null=True)),
                ('PrepTimeInMins', models.IntegerField(null=True)),
                ('CookTimeInMins', models.IntegerField(null=True)),
                ('TotalTimeInMins', models.IntegerField(null=True)),
                ('Servings', models.IntegerField(null=True)),
                ('Cuisine', models.CharField(max_length=155, null=True)),
                ('Course', models.CharField(max_length=155, null=True)),
                ('Diet', models.CharField(max_length=155, null=True)),
                ('Instructions', models.CharField(max_length=155, null=True)),
                ('TranslatedInstructions', models.CharField(max_length=256, null=True)),
                ('URL', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
