# Generated by Django 3.1.3 on 2021-02-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipie',
            name='Servings',
        ),
    ]
