# Generated by Django 3.1.3 on 2021-03-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0002_remove_recipie_servings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipie',
            name='TranslatedInstructions',
        ),
        migrations.RemoveField(
            model_name='recipie',
            name='TranslatedRecipeName',
        ),
    ]
